version: "3"
services:
  poll:
    build:
      context: ./poll
    networks:
      - poll-tier
    environment:
      REDIS_NAME: redis
    depends_on:
      - redis
    ports:
    - "5000:80"
    restart: on-failure
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379"
    networks:
      - poll-tier
      - back-tier
    restart: on-failure
  worker:
    build:
      context: ./worker
    networks:
      - back-tier
    environment:
      DB_PASSWORD: postgres
      DB_USER: postgres
      DB_NAME: db
      REDIS_NAME: redis
    depends_on:
      - db
      - redis
    restart: on-failure
  db:
    container_name: db
    image: postgres
    networks:
      - result-tier
      - back-tier
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: db
    restart: on-failure
    volumes:
      - ./:/docker-entrypoint-initdb.d/
      - db-data:/var/lib/postgresql/data
  result:
    build:
      context: ./result
    networks:
      - result-tier
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: db
      POSTGRES_SERVICE: db
    depends_on:
      - db
    ports:
    - "5001:80"
    restart: on-failure
volumes:
  db-data:
networks:
  poll-tier:
  result-tier:
  back-tier: